CONTROL_SETGAIN_CH1 = 0xE0
CONTROL_SETGAIN_CH2 = 0xE1
CONTROL_SETSAMPLERATE = 0xE2
CONTROL_STARTSAMPLING = 0xE3
CONTROL_SETNUMCHANNELS = 0xE4
CONTROL_SETCOUPLING = 0xE5
CONTROL_SETCALFREQ = 0xE6

ENDPOINT_IN = 0x86
USB_OUT = 0x40
USB_IN = 0xC0