def start_sampling(handle):
    ...

def stop_sampling(handle):
    ...

def set_samplerate(handle, sample_id, sample_index):
    ...

def set_gain_ch1(handle, gain, index):
    ...

def set_gain_ch2(handle, gain, index):
    ...